### ISSUE TITLE
Invalid line endings in cpp files under .reggen

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#14] opened 2019-02-14 13:51 UTC
Hello! I've got the following error for generated qjsonconverterreg_*.cpp files: warning C4335: Mac file format detected: please convert the source file to either DOS or UNIX format.
I suppose that wrong line endings prevent me from debugging within Visual Studio 2017.

**Comment by Skycoder42** [comment] 2019-02-14 16:46
This is stange, as those files do have UNIX-Lineendings, not Mac. Could you please attach one of the files to this issue, so I can verify this problem? Linendings should generelly not be a problem, if your git is correctly configured.

EDIT: Please upload one of the generated files, together with `src/jsonserializer/qjsonconverterreg.cpp.template` and `src/jsonserializer/qjsonserializer.cpp` - so I can better compare them

**Comment by arietto** [comment] 2019-02-19 13:45
Hello, sorry for long pause. I used Notepad++ for checking line endings.
[attachment.zip](https://github.com/Skycoder42/QtJsonSerializer/files/2880219/attachment.zip)

**Comment by Skycoder42** [comment] 2019-02-19 15:14
Okay, I have found the problem. After checking the generated cpp with a hex editor, we can see the following:
![image](https://user-images.githubusercontent.com/9221346/53025096-9d2d3080-3460-11e9-973c-9b9f53c52e53.png)

For whatever reason, we now have 2 carriage returns instead of only one (as intended). My guess is, that when the template is read by qmake, it is read in binary mode (i.e. \r\n are preseverd), but when writing, it writes in text mode, and thus converts each \n to \r\n, leading to the duplicate \r.

I already have an Idea on how to fix this.

**Comment by Skycoder42** [comment] 2019-02-19 15:51
I pushed a fix. I currently have no windows machine to verify the fix with, so please check, if this has been solved for you

**Closed as completed** 2019-02-19 15:51 UTC
Labels: need more info

**Comment by arietto** [comment] 2019-02-21 10:29
ok, thank you. That helped.
